"""Add paper_categories column

Revision ID: 04557bdf279a
Revises: cf3bdf5106c1
Create Date: 2025-04-02 21:33:17.650810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04557bdf279a'
down_revision = 'cf3bdf5106c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_categories', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.drop_column('paper_categories')

    # ### end Alembic commands ###
