"""empty message

Revision ID: 1a9e1d9d7d08
Revises: 8200d6ba3946
Create Date: 2025-04-01 19:24:31.452986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9e1d9d7d08'
down_revision = '8200d6ba3946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.String(), nullable=False))
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
