"""empty message

Revision ID: 7e3ed7cd2b1e
Revises: 1a9e1d9d7d08
Create Date: 2025-04-01 19:28:57.900948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3ed7cd2b1e'
down_revision = '1a9e1d9d7d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query', schema=None) as batch_op:
        batch_op.drop_column('response')

    # ### end Alembic commands ###
