"""empty message

Revision ID: 8200d6ba3946
Revises: 1c05d1e0eb14
Create Date: 2025-04-01 19:12:33.342920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8200d6ba3946'
down_revision = '1c05d1e0eb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('query')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=60), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=60), nullable=True),
    sa.Column('email', sa.VARCHAR(length=70), nullable=True),
    sa.Column('password', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('query',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('query', sa.VARCHAR(), nullable=False),
    sa.Column('response', sa.VARCHAR(), nullable=False),
    sa.Column('pending', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('user_query')
    # ### end Alembic commands ###
